export { default as ListView } from './ListView.vue'
export { default as DetailView } from './DetailView.vue'
export { default as FormView } from './FormView.vue'
export { controlsAt } from './controls'
export type { ViewControl, ControlPlacement } from './controls'
